/* prettier-ignore */
/* eslint-disable */
/**
 * THIS FILE IS AUTO-GENERATED by `npx convex dev`.
 * This is a stub — run `npx convex dev` to replace it with real types.
 */
import { anyApi } from "convex/server";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const api: any = anyApi;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const internal: any = anyApi;
