/* prettier-ignore */
/* eslint-disable */
/**
 * THIS FILE IS AUTO-GENERATED by `npx convex dev`.
 * This is a stub — run `npx convex dev` to replace it with real types.
 */
// @ts-nocheck
import type { GenericId } from "convex/values";

export type Id<T extends string> = GenericId<T>;
export type TableNames = "products" | "orders";
export type DataModel = any;
