/* prettier-ignore */
/* eslint-disable */
/**
 * THIS FILE IS AUTO-GENERATED by `npx convex dev`.
 * This is a stub — run `npx convex dev` to replace it with real types.
 */
import {
  queryGeneric as query,
  mutationGeneric as mutation,
  actionGeneric as action,
  internalQueryGeneric as internalQuery,
  internalMutationGeneric as internalMutation,
  internalActionGeneric as internalAction,
  httpActionGeneric as httpAction,
} from "convex/server";

export { query, mutation, action, internalQuery, internalMutation, internalAction, httpAction };
